services:
  # Backend Web Service
  - type: web
    name: servix-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://servix-server.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend Static Site
  - type: static
    name: servix-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://servix-college-project.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://servix-college-project.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
